### ISSUE TITLE
Intermittent Cypress test failures

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-editor-deployment#214] opened 2023-03-07 13:31 UTC
### Description

For the past couple of weeks, the cypress tests on the [build, test, deploy workflow](https://github.com/EasyDynamics/oscal-editor-deployment/actions/workflows/container-test-deploy.yml) have been failing more frequently.

### Steps to Reproduce

View the workflow failures such as

- https://github.com/EasyDynamics/oscal-editor-deployment/actions/runs/4354049162/jobs/7608869123
- https://github.com/EasyDynamics/oscal-editor-deployment/actions/runs/4323346922/jobs/7546847878

### What has been done so far

- Docker logs do not provide any obvious problems
- Cypress results also just show normal loading issues like seen in the past
- The tests failing usually mention a time out of some sort
- The `cypress` dependency recently updated from 12.6.0 to [12.7.0](https://github.com/cypress-io/cypress/releases/tag/v12.7.0), but it doesn't seem like that would cause issues. 

### Expected Behavior

The `Drawer.cy.js` tests rarely fail and all other tests pass.   

Ideally the tests should never fail if things are working correctly, but due to some issues with loading speed 100% passing is not always the case. It should pass with a second attempt. 

### Actual Behavior

The tests are failing pretty regular and sometimes even beyond a second rerun of the workflow. What is even more odd is that the failures are no longer constrained to just `Drawer.cy.js` tests.

**Comment by tuckerzp** [comment] 2023-03-10 16:41
### Status Update

This task is between 20% - 75% done. The percentage could change very drastically depending on input from team, if something pops up that I've been missing, etc. It is also a bit tricky to assign a value of completeness to looking into an issue. 

### Details

I have been a bit stuck trying to find where the issue lies. I am still looking for some strand to pull to begin fixing the problem. That could happen very quickly or may take a bit.

**Comment by kylelaker** [comment] 2023-03-10 16:50
These `Broken Pipe` errors are interesting -- and I am curious which side the failure is happening on. Is Cypress closing the connection quickly because the timeout was already hit and it's moving on? Or is some server-side timeout being hit and the pipe is being closed?

**Comment by Bronstrom** [comment] 2023-03-10 20:50
3/10/23 Sprint Planning - Moved from Sprint 42 to Sprint 43

**Comment by kylelaker** [comment] 2023-03-14 18:33
Okay so we're now in a slightly better place. We have merged a few PRs today and we haven't seen any test failures on `main` yet. I **do not** like our "fix" which is really more of a hotfix. Primarily we fixed a bug caused by a recent PR merged on `oscal-react-library` which did not have corresponding updates to the end-to-end tests (we need to retro that and see if we can catch similar things in the future). Additionally, we significantly increased the waits before timing out across the application; like in some cases up to a minute. This *is not* acceptable in the long-term but it gets us over this immediate hurdle.

Initially, things indicate that it is likely the backend that is operating slowly. We are seeing that even locally doing a `curl http://localhost:8080/oscal/v1/catalogs` takes ~15s due to the validation failures that we are seeing (super unfortunate) and other processing (TODO: make sure logging isn't in the "hot path" for actually sending the response). We have issues like https://github.com/EasyDynamics/oscal-rest/issues/55 to start returning "partial" objects but we need to look into that more.

I do not want to close this yet; I would like to keep it open for a few more days. @tuckerzp please keep monitoring for failures on the workflow on the main branch and on PRs; keep a tally and report them separately on Monday so we can see if this is actually getting better.

In the meantime, we can resume merging PRs on this repository and elsewhere that we held until after the tests were reliably passing again.

**Comment by tuckerzp** [comment] 2023-03-14 18:47
> keep monitoring for failures on the workflow on the main branch and on PRs

I will update this comment to reflect all failing runs. 

### Failures

- n/a

**Comment by kylelaker** [comment] 2023-03-14 20:11
Manually triggered https://github.com/EasyDynamics/oscal-editor-deployment/actions/runs/4419699144/jobs/7748456949 to pick up https://github.com/EasyDynamics/oscal-rest-service/pull/178

**Comment by kylelaker** [comment] 2023-03-17 19:21
Okay I am now feeling **a lot** better about this. Here are some of the changes that have been made to support this:

1. Waiting between starting the container and running the tests - https://github.com/EasyDynamics/oscal-editor-deployment/pull/228
1. Increasing the timeout to ~60s (I don't love this but it's helpful to make sure it's not actually errors in the tests, we need to set better performance goals and then can tighten this a bit)  - https://github.com/EasyDynamics/oscal-editor-deployment/pull/218 
1. Using a better base image - https://github.com/EasyDynamics/oscal-editor-deployment/pull/221
1. General workflow refactoring - https://github.com/EasyDynamics/oscal-editor-deployment/pull/226
1. Preventing logging constraint validation errors from slowing down responses - https://github.com/EasyDynamics/oscal-rest-service/pull/182

The next step we might be able to take is to _temporarily_ disable constraint validation in the OSCAL REST Service until issues with the catalog validation are resolved.

**Comment by kylelaker** [comment] 2023-03-23 20:24
Okay and the fixes that were just merged in #232 should be the last thing needed for us to stop seeing intermittent failures in the tests. We haven't seen any on the main branch that I am aware of this week. I am going to close this and we can either reopen (or create a new issue) if we see failures again.

**Closed by kylelaker** 2023-03-23 20:24 UTC
Labels: bug
